[
  {
    de: 'Veranstaltungen',
    en: 'Events',
    es: 'Eventos',
    fr: 'Événements',
    it: 'Eventi',
    pl: 'Wydarzenia',
    ru: 'События',
    sw: 'Händelser',
  },
  {
    de: 'Heim',
    en: 'Home',
    es: 'Hogar',
    fr: 'Maison',
    it: 'Casa',
    pl: 'Dom',
    ru: 'Главная',
    sw: 'Hem',
  },
  {
    de: 'Geschäft',
    en: 'Shop',
    es: 'Comercio',
    fr: 'Boutique',
    it: 'Negozio',
    pl: 'Sklep',
    ru: 'Магазин',
    sw: 'Handla',
  },
  {
    de: 'Warenkorb',
    en: 'Cart',
    es: 'Cesta',
    fr: 'Panier',
    it: 'Carrello',
    pl: 'Wózek',
    ru: 'Корзина',
    sw: 'Vagn',
  },
  {
    de: 'Konto',
    en: 'Account',
    es: 'Cuenta',
    fr: 'Compte',
    it: 'Account',
    pl: 'Konto',
    ru: 'Аккаунт',
    sw: 'Konto',
  },
  {
    de: 'Avatar ändern',
    en: 'Change avatar',
    es: 'Cambiar avatar',
    fr: 'Changer avatar',
    it: 'Cambia avatar',
    pl: 'Zmień awatar',
    ru: 'Изменить аватар',
    sw: 'Byt avatar',
  },
  {
    de: 'Speichern',
    en: 'Save',
    es: 'Ahorrar',
    fr: 'Sauvegarder',
    it: 'Salva',
    pl: 'Ratować',
    ru: 'Сохранить',
    sw: 'Spara',
  },
  {
    de: 'Ändern',
    en: 'Change',
    es: 'Cambiar',
    fr: 'Changement',
    it: 'Modifica',
    pl: 'Zmiana',
    ru: 'Изменить',
    sw: 'Ändra',
  },
  {
    de: 'Ihr Name',
    en: 'Your Name',
    es: 'Su nombre',
    fr: 'Votre nom',
    it: 'Il tuo nome',
    pl: 'Twoje imię',
    ru: 'Ваше имя',
    sw: 'Ditt namn',
  },
  {
    de: 'Sprache auswählen',
    en: 'Choose Language',
    es: 'Seleccionar idioma',
    fr: 'Choisir la langue',
    it: 'Scegli la lingua',
    pl: 'Wybierz język',
    ru: 'Выберите язык',
    sw: 'Välj Språk',
  },
  {
    de: 'Der Name muss mindestens 3 Zeichen enthalten',
    en: 'Name should contain atleast 3 character',
    es: 'El nombre debe contener al menos 3 caracteres.',
    fr: 'Le nom doit contenir au moins 3 caractères',
    it: 'Il nome deve contenere almeno 3 caratteri',
    pl: 'Nazwa powinna zawierać co najmniej 3 znaki',
    ru: 'Имя должно содержать не менее 3 символов.',
    sw: 'Namnet bör innehålla minst 3 tecken',
  },
  {
    de: 'Befehl',
    en: 'Order',
    es: 'Orden',
    fr: 'Commande',
    it: 'Ordine',
    pl: 'Zamówienie',
    ru: 'Заказ',
    sw: 'Beställa',
  },
  {
    de: 'Zwischensumme',
    en: 'Sub Total',
    es: 'Subtotal',
    fr: 'Sous-total',
    it: 'Subtotale',
    pl: 'Podsuma',
    ru: 'Подытог',
    sw: 'Subtotal',
  },
  {
    de: 'Steuer',
    en: 'Tax',
    es: 'Impuesto',
    fr: 'Impôt',
    it: 'Tassare',
    pl: 'Podatek',
    ru: 'Налог',
    sw: 'Beskatta',
  },
  {
    de: 'Gesamtbetrag',
    en: 'Total Amount',
    es: 'Importe total',
    fr: 'Montant total',
    it: 'Importo totale',
    pl: 'Całkowita kwota',
    ru: 'Общая сумма',
    sw: 'Totalt belopp',
  },
  {
    de: 'Anwenden',
    en: 'Apply',
    es: 'Aplicar',
    fr: 'Appliquer',
    it: 'Aplicar',
    pl: 'Stosować',
    ru: 'Применять',
    sw: 'Tillämpas',
  },
  {
    de: 'Bestellung aufgeben',
    en: 'Place Order',
    es: 'Realizar pedido',
    fr: 'Passer une commande',
    it: "Effettuare l'ordine",
    pl: 'Złóż zamówienie',
    ru: 'Разместить заказ',
    sw: 'Lägg beställning',
  },
  {
    de: 'Aktionscode',
    en: 'Promo Code',
    es: 'Código promocional',
    fr: 'Code promotionnel',
    it: 'Codice promozionale',
    pl: 'Kod promocyjny',
    ru: 'Промо-код',
    sw: 'Kampanjkod',
  },
  {
    de: 'Zeigen Sie diesen Code dem Kellner',
    en: 'Show this code to the waiter',
    es: 'Muestra este código al camarero.',
    fr: 'Montrez ce code au serveur',
    it: 'Mostra questo codice al cameriere',
    pl: 'Pokaż ten kod kelnerowi',
    ru: 'Покажите этот код официанту',
    sw: 'Visa denna kod för servitören',
  },
  {
    de: 'salate',
    en: 'salads',
    es: 'ensaladas',
    fr: 'insalate',
    it: 'insalate',
    pl: 'sałatki',
    ru: 'салаты',
    sw: 'sallader',
  },
  {
    de: 'Vorspeisen',
    en: 'starters',
    es: 'Entrantes',
    fr: 'entrées',
    it: 'antipasti',
    pl: 'przystawki',
    ru: 'закуски',
    sw: 'förrätter',
  },
  {
    de: 'Nachspeisen',
    en: 'desserts',
    es: 'postres',
    fr: 'desserts',
    it: 'dolci',
    pl: 'hello',
    ru: 'десерты',
    sw: 'desserter',
  },
  {
    de: 'Getränke',
    en: 'drinks',
    es: 'bebidas',
    fr: 'boissons',
    it: 'bevande',
    pl: 'hello',
    ru: 'напитки',
    sw: 'drycker',
  },
  {
    de: 'Toute',
    en: 'All',
    es: 'Todo',
    fr: 'Alle',
    it: 'Tutto',
    pl: 'Wszystko',
    ru: 'Все',
    sw: 'Alla',
  },
  {
    de: 'Kategorie wählen',
    en: 'Select category',
    es: 'Seleccionar categoría',
    fr: 'Sélectionnez une catégorie',
    it: 'Seleziona la categoria',
    pl: 'Wybierz kategorię',
    ru: 'Выберите категорию',
    sw: 'Välj kategori',
  },
  {
    de: 'Hinzufügen',
    en: 'Add',
    es: 'Agregar',
    fr: 'Ajouter',
    it: 'Aggiungere',
    pl: 'Dodać',
    ru: 'Добавить',
    sw: 'Tillägga',
  },
  {
    de: 'Hinzugefügt',
    en: 'Added',
    es: 'Agregado',
    fr: 'Ajouté',
    it: 'Aggiunto',
    pl: 'W dodatku',
    ru: 'Добавлено',
    sw: 'Tillagd',
  },
  {
    de: 'Sendungen',
    en: 'Broadcasts',
    es: 'Transmisiones',
    fr: 'Diffusions',
    it: 'Trasmissioni',
    pl: 'Transmisje',
    ru: 'Трансляции',
    sw: 'Sändningar',
  },
  {
    de: 'Ihr Warenkorb ist leer',
    en: 'Your cart is empty',
    es: 'Tu carrito está vacío',
    fr: 'Votre panier est vide',
    it: 'Il tuo carrello è vuoto',
    pl: 'Twój koszyk jest pusty',
    ru: 'Ваша корзина пуста',
    sw: 'Din varukorg är tom',
  },
  {
    de: 'Tischreservierung',
    en: 'Booking',
    es: 'Reserva de mesa',
    fr: 'Réservation de table',
    it: 'Prenotazione tavolo',
    pl: 'Rezerwacja',
    ru: 'Резерв столика',
    sw: 'Bokning',
  },
  {
    de: 'Datum auswählen',
    en: 'Select date',
    es: 'Seleccionar fecha',
    fr: 'Sélectionnez une date',
    it: 'Seleziona la data',
    pl: 'Wybierz datę',
    ru: 'Выберите дату',
    sw: 'Välj datum',
  },
  {
    de: 'Wähle eine Uhrzeit',
    en: 'Select time',
    es: 'Seleccione la hora',
    fr: "Sélectionnez l'heure",
    it: "Seleziona l'ora",
    pl: 'Wybierz czas',
    ru: 'Выберите время',
    sw: 'Välj tid',
  },
  {
    de: 'Weitermachen',
    en: 'Continue',
    es: 'Continuar',
    fr: 'Continuer',
    it: 'Continuare',
    pl: 'Kontynuować',
    ru: 'Продолжить',
    sw: 'Fortsätta',
  },
  {
    de: 'Buch',
    en: 'Book now',
    es: 'Libro',
    fr: 'Réserve',
    it: 'Libro',
    pl: 'Zarezerwuj teraz',
    ru: 'Забронировать',
    sw: 'Boka nu',
  },
  {
    de: 'Ihr Telefon',
    en: 'Your phone',
    es: 'Tu teléfono',
    fr: 'Votre téléphone',
    it: 'Il tuo telefono',
    pl: 'Twój telefon',
    ru: 'Ваш телефон',
    sw: 'Din telefon',
  },
  {
    de: 'E-mail',
    en: 'E-mail',
    es: 'E-mail',
    fr: 'E-mail',
    it: 'E-mail',
    pl: 'E-mail',
    ru: 'E-mail',
    sw: 'E-mail',
  },
  {
    de: 'Auf dieser Seite können Sie einen Tisch für den von Ihnen gewünschten Termin reservieren.',
    en: 'On this page you can book a table for the date you are interested in.',
    es: 'En esta página podrás reservar mesa para la fecha que te interese.',
    fr: 'Sur cette page, vous pouvez réserver une table pour la date qui vous intéresse.',
    it: 'In questa pagina puoi prenotare un tavolo per la data che ti interessa.',
    pl: 'Na tej stronie możesz zarezerwować stolik na interesujący Cię termin.',
    ru: 'На этой странице вы можете забронировать столик на интересующую вас дату.',
    sw: 'På denna sida kan du boka bord för det datum du är intresserad av.',
  },
  {
    de: 'Füllen Sie ein einfaches Formular aus und unsere Manager werden Sie in Kürze kontaktieren.',
    en: 'Fill out a simple form and our managers will contact you shortly.',
    es: 'Complete un sencillo formulario y nuestros gerentes se comunicarán con usted en breve.',
    fr: 'Remplissez un simple formulaire et nos gestionnaires vous contacteront sous peu.',
    it: 'Compila un semplice modulo e i nostri responsabili ti contatteranno al più presto.',
    pl: 'Wypełnij prosty formularz, a nasi menedżerowie wkrótce się z Tobą skontaktują.',
    ru: 'Заполните простую форму и наши менеджеры свяжутся с вами в ближайшее время.',
    sw: 'Fyll i ett enkelt formulär så kontaktar våra chefer dig inom kort.',
  },
  {
    de: 'Ihr Tisch wurde erfolgreich reserviert!',
    en: 'Your table has been successfully booked!',
    es: '¡Su mesa ha sido reservada con éxito!',
    fr: 'Votre table a été réservée avec succès !',
    it: 'Il tuo tavolo è stato prenotato con successo!',
    pl: 'Twój stolik został pomyślnie zarezerwowany!',
    ru: 'Ваш столик успешно забронирован!',
    sw: 'Ditt bord har bokats!',
  },
  {
    de: 'Unsere Manager werden sich in Kürze mit Ihnen in Verbindung setzen.',
    en: 'Our managers will contact you shortly.',
    es: 'Nuestros responsables se pondrán en contacto con usted en breve.',
    fr: 'Nos responsables vous contacteront sous peu.',
    it: 'I nostri responsabili ti contatteranno a breve.',
    pl: 'Nasi menedżerowie wkrótce się z Tobą skontaktują.',
    ru: 'Наши менеджеры свяжутся с вами в ближайшее время.',
    sw: 'Våra chefer kommer att kontakta dig inom kort.',
  },
  {
    de: 'Meisterkurs zum Pizzabacken',
    en: 'Pizza Making Master Class',
    es: 'Clase magistral de elaboración de pizza',
    fr: 'Master class de préparation de pizza',
    it: 'Masterclass sulla preparazione della pizza',
    pl: 'Kurs mistrzowski robienia pizzy',
    ru: 'Мастер-класс по приготовлению пиццы',
    sw: 'Masterklass för pizzatillverkning',
  },
  {
    de: 'Mini-Fußballmeisterschaft für Kinder',
    en: "Children's Mini-Football Championship",
    es: 'Campeonato de minifútbol infantil',
    fr: 'Championnat de mini-football pour enfants',
    it: 'Campionato di calcetto infantile',
    pl: 'Mistrzostwa Dzieci w Mini Piłce Nożnej',
    ru: 'Чемпионат по десткому мини-футболу',
    sw: 'Barnmästerskap i minifotboll',
  },
  {
    de: 'Sport: Legenden und Mythen',
    en: 'Sports: Legends and Myths',
    es: 'Deportes: Leyendas y Mitos',
    fr: 'Sports: légendes et mythes',
    it: 'Sport: leggende e miti',
    pl: 'Sport: legendy i mity',
    ru: 'Спорт: Легенды и Мифы',
    sw: 'Sport: Legender och myter',
  },
  {
    de: 'Fußballabend',
    en: 'Football evening',
    es: 'Noche de fútbol',
    fr: 'Soirée foot',
    it: 'Serata di calcio',
    pl: 'Wieczór piłkarski',
    ru: 'Футбольный вечер',
    sw: 'Fotbollskväll',
  },
  {
    de: 'Köstliche mexikanische Tacos kochen',
    en: "Let's cook a delicious Mexican taco",
    es: 'Cocinar deliciosos tacos mexicanos',
    fr: 'Cuisiner de délicieux tacos mexicains',
    it: 'Cucinare deliziosi tacos messicani',
    pl: 'Gotowanie pysznych meksykańskich tacos',
    ru: 'Готовим вкусный мексиканский тако',
    sw: 'Lagar läckra mexikanska tacos',
  },
  {
    de: 'Autorennen-Rallye 2024',
    en: 'Auto racing 2024 Rally',
    es: 'Rally de carreras de autos 2024',
    fr: 'Rallye de course automobile 2024',
    it: 'Corse automobilistiche Rally 2024',
    pl: 'Rajd wyścigów samochodowych 2024',
    ru: 'Автогонки 2024 Ралли',
    sw: 'Autoracing 2024 Rally',
  },
  {
    de: "Vortrag 'Gesunde Ernährung'",
    en: "Lecture 'Healthy Nutrition'",
    es: "Conferencia 'Alimentación saludable'",
    fr: "Conférence 'Alimentation saine'",
    it: "Conferenza 'Mangiare sano'",
    pl: "Wykład 'Zdrowe odżywianie'",
    ru: "Лекция 'Здоровое питание'",
    sw: "Föreläsning 'Hälsosam kost'",
  },
  {
    de: 'Meisterklasse',
    en: 'master class',
    es: 'clase magistral',
    fr: 'classe de maître',
    it: 'lezione magistrale',
    pl: 'klasa mistrzowska',
    ru: 'мастер-класс',
    sw: 'mästarklass',
  },
  {
    de: 'Rennen schauen',
    en: 'watching races',
    es: 'viendo carreras',
    fr: 'regarder des courses',
    it: 'guardare le gare',
    pl: 'oglądanie wyścigów',
    ru: 'просмотр гонок',
    sw: 'tittar på lopp',
  },
  {
    de: 'Vortrag eines Ernährungsberaters',
    en: 'lecture from a nutritionist',
    es: 'conferencia de un nutricionista',
    fr: "conférence d'un nutritionniste",
    it: 'conferenza di un nutrizionista',
    pl: 'wykład dietetyka',
    ru: 'лекция от нутрициолога',
    sw: 'föreläsning från en dietist',
  },
  {
    de: 'Quest in der virtuellen Realität',
    en: 'Quest in virtual reality',
    es: 'Búsqueda en realidad virtual',
    fr: 'Quête en réalité virtuelle',
    it: 'Ricerca nella realtà virtuale',
    pl: 'Poszukiwanie w wirtualnej rzeczywistości',
    ru: 'Квест в  виртуальной реальности',
    sw: 'Quest i virtuell verklighet',
  },
  {
    de: 'Fußballwochenende',
    en: 'lecture',
    es: 'Fin de semana de fútbol',
    fr: 'Week-end de foot',
    it: 'Fine settimana di calcio',
    pl: 'Piłkarski weekend',
    ru: 'Футбольный уикенд',
    sw: 'Fotbollshelg',
  },
  {
    de: 'Abend mit indischer Küche',
    en: 'Indian Cuisine Evening',
    es: 'Noche de cocina india',
    fr: 'Soirée Cuisine Indienne',
    it: 'Serata di cucina indiana',
    pl: 'Wieczór Kuchni Indyjskiej',
    ru: 'Вечер индийской кухни',
    sw: 'Indiskt kökskväll',
  },
  {
    de: 'Basketball-Wochenende',
    en: 'Basketball weekend',
    es: 'Fin de semana de baloncesto',
    fr: 'Week-end de basket',
    it: 'Fine settimana di basket',
    pl: 'Koszykarski weekend',
    ru: 'Баскетбольный уикенд',
    sw: 'Basket helg',
  },
];
